$script = <<SCRIPT
sudo puppet module install puppetlabs-apt
SCRIPT

Vagrant::Config.run do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  config.vm.forward_port 9090, 9090

  config.vm.provision "shell", inline: $script
  config.vm.provision "puppet"

end